theme: jekyll-theme-cayman


# Site settings 
title: Forgeeks博客 
SEOTitle: Forgeeks博客 
header-img: img/bg.jpg  
email: forgeekscn@gmail.com 
description: "Forgeeks博客" 
keyword: "Forgeeks博客, Java ,大数据, 架构" #关键词 
url: "https://forgeekscn.github.io" # 这个就是填写你的博客地址 
baseurl: "" # 这个我们不用填写
 
 
 sidebar: true 
 sidebar-about-description: "forgeekscn" 
 sidebar-avatar:/img/me.png 

 